[workspace]
resolver = "2"
members = [
    "inputflow",
    "inputflow-native",
    "inputflow-kmbox",
    "inputflow-example-loader"
]
default-members = [
    "inputflow",
    "inputflow-native",
    "inputflow-kmbox",
    "inputflow-example-loader"
]
